### ISSUE TITLE
pathologically bad behaviour on very large tables

### ISSUE THREAD

**Issue by philpennock** [apcera/termtables#29]
While clearly the normal use-case for `termtables` is "about how many rows might reasonably fit in a terminal window at once, or about as many as it makes sense to send straight out", we should not behave unduly badly when given a table with many many rows.

Given 29215 rows of data (and 261 dividers) across 10 columns, it takes just over 3 minutes for `fmt.Fprint(..., t.Render())` using 160% CPU on a 1.2 GHz Intel Core M processor (early 2015 Macbook).

**Comment by johnSchnake** [comment]
Big improvement in render speed here: https://github.com/apcera/termtables/pull/35

After that if we still wanted to improve it we _could_ add a method that streams the output to a reader that can be copied as desired. The `Render` code could then just be a wrapper that drains the reader and returns the value.

**Comment by johnSchnake** [comment]
Closing; this seems to no longer be an issue.

Given the test program:
```
	testCases := []struct {
		maxRow, maxCol int
		duration       time.Duration
	}{
		{maxRow: 10, maxCol: 10},
		{maxRow: 100, maxCol: 10},
		{maxRow: 1000, maxCol: 10},
		{maxRow: 10000, maxCol: 10},
		{maxRow: 100000, maxCol: 10},
	}

	for i, tc := range testCases {
		t := termtables.CreateTable()
		for r := 0; r < tc.maxRow; r++ {
			row := t.AddRow()
			for c := 0; c < tc.maxCol; c++ {
				row.AddCell("item")
			}
		}
		begin := time.Now()
		fmt.Printf(t.Render())
		testCases[i].duration = time.Now().Sub(begin)
	}

	t := termtables.CreateTable()
	t.AddHeaders("Rows", "Columns", "Time to Render")
	for _, tc := range testCases {
		t.AddRow(tc.maxRow, tc.maxCol, tc.duration)
	}
	fmt.Println(t.Render())
```
I got the following output (besides all the junk table output; I wanted that to still go to the terminal so that I saw real behavior and not a different speed due to using a plain buffer):
```
+--------+---------+----------------+
| Rows   | Columns | Time to Render |
+--------+---------+----------------+
| 10     | 10      | 144.002µs      |
| 100    | 10      | 1.250394ms     |
| 1000   | 10      | 32.245872ms    |
| 10000  | 10      | 133.456814ms   |
| 100000 | 10      | 1.470458528s   |
+--------+---------+----------------+
```
So if I understood your test case (~30,000 rows, 10 columns) it is about 1/2 second.
